ARMY_ORE = 1 
ARMY_SHEEP = 1
VILLAGE_GRAIN = 2
VILLAGE_SHEEP = 1
FORT_ORE = 1
FORT_GRAIN = 1
FORT_WOOD = 1
CITY_ORE = 1
CITY_WOOD = 2
CITY_SHEEP = 1

STARTING_GRAIN = 1
STARTING_ORE = 1
STARTING_SHEEP = 1
STARTING_WOOD = 1

SUPPORT_STRENGTH = 1
